#862kk57hf Разработка карточек салонов
MyNameIsNeXTSTEP/Fixmaster pull request #9
Opened 2023-11-16 18:25 UTC by mandz1952

[#862kk57hf](https://app.clickup.com/t/862kk57hf) Разработка карточек салонов

2023-11-21 16:40 UTC, MyNameIsNeXTSTEP requested changes

2023-11-21 16:40 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +import Card from 'react-bootstrap/Card';
Лучше бы как-то переименовать компонент получше, т.к. уже SalonCard есть, а тут хоть и в множественном числе, но все равно выглядит одинаково, кто знает, какие ещё новые компоненты будут или как текущие будут декомпозированы дальше. Также правильно на англ. будет Saloon c 2-мя `о`

Можно переименовать в `SaloonCardsSet`

2023-11-21 16:40 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +function BasicExample({id}: ISaloon) {
Если это компонент, см. тех.регламент и замечания:
1. Не использовать function declaration, использовать callback `const Component = ({ … }: IProps): JSX.Element => { … return <></>}`
2. Правильно именовать компонент, тут он должен как и файл

2023-11-21 16:40 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +        const min = new Date().getMinutes()
Описано очень алгоритмично и тяжело поддерживаемо, даже при 2-3 чтения подряд другой разраб, я, просто так не поймём что это и для чего конкретно, хотя в целом и ясно, что что-то для рабочего времени. Имеется в виду всё, что в useEffect.

Если получается - исправить сейчас желательно, если займёт это больше чем 30-60 минут исправление, оставляй коммент `// @todo Refactoring, need to simplify code and make more readable`

---

К тому же, это всё не должно по хорошему лежать внутри useEffect(а), как минимум, разнесено по разным колбэкам и потом скомпилировано в эффекте.

2023-11-21 16:40 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
Снова, не используем такие импорты и тайп-кастинг.
Используем только 'import' модулей в шапке файла чистый.
+ Назови переменуню по другому, просто `map` - не понятно, что за карта, что за тип объекта.

2023-11-21 16:40 UTC, MyNameIsNeXTSTEP commented on src/pages/MainPage.tsx
> +            {salonsData.map(i => {
Код-стайл, не используй простое `i` для именования элемента, хотя бы `saloon` просто

2023-11-22 10:54 UTC, MyNameIsNeXTSTEP requested changes

2023-11-22 10:54 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +import Card from 'react-bootstrap/Card';
Но если что не настаиваю, пересмотрел своё решение, можно оставить и ка ку тебя, на твоё усмотрение.

2023-11-22 10:54 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +        const hourEnd = Number(timeEnd.split(':')[0])
Названия всё равно не очень у переменных, именование - одна из важнейших вещей. Да, тут хоть скуп и небольшой, понятно то речь про карточки салонов, но непонятно всё же, что за end, start.

Именование нужно такое: `workStartTimeInHours`, `workEndTimeInHours` и т.д.
Код всё равно процедурный остался, не объектный, не функциональный, а просто набор посчитало (алгоритм), чтобы его потом понять кому-то, нужно будет читать и вдумываться, исправлять, тратить время.

---

А ещё лучше будет, если манипуляции с часами и минутами будут в отдельных методах / классах / функциях, как-то так.

2023-11-23 21:36 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
выдает ошибку
TS2307: Cannot find module '../../assets/map-pin.svg' or its corresponding type declarations.
раньше я тоже подобный импорт только использовал

2023-11-24 15:27 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
@mandz1952 Надо почитать об ошибке, значит, как всегда, погуглить, в первую очередь.
Тут дело в типах экспорта/импорта, они бывают разные в JS (стандартные, модульные…), также влияет конфигурация тайпскрипта, в чём собственно и дело.

В данном случае можно так решить оптимальнее всего, добавь это в **tsconfig** в конец: `"include": ["./src/**/*"],`

2023-11-24 15:29 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +        const min = new Date().getMinutes()
Или вовсе убери include секцию*

2023-11-24 15:30 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
Или вовсе убери include секцию*

2023-11-24 15:38 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
я так уже пробовал, не получалось, то что я смог нагуглить, без доп файлов и подобных импортов, это сделать svg как элемент в tsx файле и использовать его как элемент, если так можно, то могу так сделать

2023-11-25 13:22 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
Можно, конечно, если пока иначе не получается. Но в целом далее будет лучше такой подход: вся статика хранится отдельно в /assets, а есть только один компонент-презентатор типа `SVGMedia`, который в себя просто src принимает нужной сег-шки и становится медиа-компонентом, н ов целом, не помешает тебе и разобраться, как можно так сделать, если получится.

2023-11-25 15:41 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
сейчас сделаю, а почему через require нельзя импортировать?

2023-11-25 15:56 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
1. Есть стайл-гайд принятый
2. Определённый тип импортов связан с модульной системой, принятой в проекте, см:
- https://thecontentauthority.com/blog/require-vs-import
- https://stackoverflow.com/questions/31354559/using-node-js-require-vs-es6-import-export
3. Консистентность - везде всему следует быть однообразному.

2023-11-25 15:59 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
![Uploading Screenshot 2023-11-25 at 18.58.53.png…]()

2023-11-25 19:00 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +        const hourEnd = Number(timeEnd.split(':')[0])
готово

2023-11-25 19:00 UTC, mandz1952 commented on src/pages/MainPage.tsx
> +            {salonsData.map(i => {
готово

2023-11-25 19:00 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +    const map = require('../../assets/map-pin.svg') as string;
готово

2023-11-25 19:00 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +        const min = new Date().getMinutes()
готово

2023-11-25 19:00 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +function BasicExample({id}: ISaloon) {
готово

2023-11-25 19:00 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +import Card from 'react-bootstrap/Card';
готово

2023-11-27 11:54 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +
Лишняя пустая строка

2023-11-27 11:54 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +class CalcTime {
Классы лучше называть именами существительными, т.е. что они собой представляют именно для нас, в данном случае это будет `SalonWorkTime`, а имена методов глаголами, т.к. мы общаемся с объектами, говоря им, о чём мы их просим.

2023-11-27 11:54 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +            const timeType:Intl.RelativeTimeFormatUnit = 'minute'
Объявление `const timeType` выглядит как лишняя операция, внутрь кладётся лишь строка 'minutes' или 'hours' ниже. Также нет смысла в переходной переменной `const time = minutes`, когда можно использовать сразу `minutes`.

Еще момент, что возвращается объект: `{ 'minutes',  minutes}` или `{ 'hours',  hours}` ниже.
Т.е. объект, у которого описания сущности и значение лежат отдельно, а не вместе вот так, как следовало бы: `{ 'minutes': minutes }` и `{ 'hours':  hours}`, тут как видишь поле одно ключ: значение, а не два отдельных поля.

Если так именно и учитывая типы принимает эта библиотека, что ты привнёс, то попробуй как-то всё-таки причесать по замечаниям выше, если не выходит, пиши сюда или в задаче.

2023-11-27 11:54 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +
Лишняя пустая строка и объявление компонента не сделал по регламенту и замечанию в существующем треде - https://github.com/MyNameIsNeXTSTEP/Fixmaster/pull/9#discussion_r1400867931

2023-11-27 11:54 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +function BasicExample({id}: ISaloon) {
Не готово, нет исправлений

2023-11-27 11:54 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +        const workEndTimeInHours = Number(timeEnd.split(':')[0])
Оставь всё-таки коммент, как я просил тут, для рефакторинг, всё же надо будет привести в порядок в дальнейшем, сейчас слишком алгоритмично видится это

2023-11-27 11:55 UTC, MyNameIsNeXTSTEP commented on src/pages/MainPage.tsx
> +            {salonsData.map(i => {
Не вижу исправлений

2023-11-27 15:21 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +function BasicExample({id}: ISaloon) {
тут тоже вроде исправленно и локально, и в гитхабе

2023-11-27 18:01 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +function BasicExample({id}: ISaloon) {
Возвращаемый тип компонента отсутствует

2023-11-27 18:27 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +            const timeType:Intl.RelativeTimeFormatUnit = 'minute'
Ответственность расчёта флага открыт/закрыт салона лежит на бэкенде, фронт должен оперировать только time_begin и time_end из АПИ и выдавать что-то типа `status ? Закроется в …` Откроется в …`

2023-11-28 15:20 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +
готово

2023-11-28 15:21 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +class CalcTime {
готово(убрал полностью весь лишний код)

2023-11-28 15:21 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +            const timeType:Intl.RelativeTimeFormatUnit = 'minute'
готово

2023-11-28 15:21 UTC, mandz1952 commented on src/Components/SalonsCards/SalonsCards.tsx
> +
готово

2023-12-01 19:48 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +
не готово, лишняя пустая строка всё ещё присутствует

2023-12-01 19:48 UTC, MyNameIsNeXTSTEP commented on src/Components/SalonsCards/SalonsCards.tsx
> +
тут тоже не нужно, лишние пустые строки игнорируем

2023-12-01 19:48 UTC, MyNameIsNeXTSTEP commented on src/pages/MainPage.tsx
> +
Аналогично, пустая строка

2023-12-10 14:45 UTC, MyNameIsNeXTSTEP approved these changes

2023-12-10 14:45 UTC, merged